---
title: "Bayer CHAPTER"
---

Welcome to the Bayer CHAPTER study. This study aims to describe patient characteristics and treatment pathways of women diagnosed with menopause in real-world data sources that have been standardized to the OMOP CDM.

# Contact

-   Study Coordinators:
    -   Victoria Banks 
    -   Siir Su Saydam 
    -   Carina Dinkel-Keuthage 
-   Study Code Developers:
    -   Martin Lavallee [(email)](mailto:martin.lavallee@odysseusinc.com)
    -   George Argyriou [(email)](mailto:george.argyriou@odysseusinc.com)

# Navigation

-   **Technical Info**:
    -   **Requirements**: Information on setting up the OHDSI environment for the study
    -   **News**: The latest updates to the study code
-   **Study Info**:
    -   **Analysis Plan**: The study's analysis plan
    -   **How-To-Run**: Information on how to run the study
    -   **Contribution Guidelines**: Information on how to contribute to the study
-   **Study Code**: Click on the Github logo on the top right of the page to find the study code

# Participating Databases

This study will be run on OMOP databases. The table below lists the databases that the study package has been run.

| Database                     | Country        |
|------------------------------|----------------|
| Truven MarketScan            | United States  |
| Optum Clinformatics          | United States  |
| CPRD GOLD                    | United Kingdom |
| CPRD AURUM                   | United Kingdom |

